# Generated by Django 3.1.6 on 2021-06-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Officer_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Officer', models.CharField(max_length=200)),
                ('Violator', models.CharField(max_length=200)),
                ('LicenseNo', models.CharField(blank=True, max_length=200)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Violation', models.IntegerField(choices=[('No Drivers License', 'no drivers license'), ('Expired Drivers License', 'expired drivers license'), ('Drunk Driving', 'drunk driving'), ('Reckless Driving', 'reckless driving'), ('No MC Helmet', 'no mc helmet'), ('OR/CR Or Drivers License Not Carried', 'or/cr or drivers license not carried'), ('Fake OR/CR And Sticker', 'fake or/or plates and sticker'), ('Driving With Defective Parts And Accessories', 'driving with defective parts and accessories'), ('No Sign Board', 'no sign board'), ('Unregistered Motor Vehicle', 'unregistered motor vehicle'), ('Improvised/Unauthorized Mutter', 'improvised/unauthorized mutter'), ('No Signal Lights', 'no signal lights'), ('No Tail Lights', 'no tail lights'), ('No Head Lights', 'no head lights'), ('No Side Mirrors', 'no side mirrors'), ('No Horns', 'no horns'), ('Defective Brake', 'defective brake'), ('Illegal Parking', 'illegal parking'), ('Dirty/No/Not Firmly Attached Plate Number', 'dirty/no/not firmly attached plate number'), ('Obstruction', 'obstruction')], max_length=200)),
                ('Fine', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DueDate', models.DateField()),
                ('Status', models.CharField(choices=[('Pending', 'pending'), ('Penalty', 'penalty'), ('Settled', 'settled')], default='pending', max_length=200)),
                ('Ticket', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='VTraffic.officer_page')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FineAmount', models.FloatField()),
                ('Status', models.CharField(choices=[('Pending', 'pending'), ('Penalty', 'penalty'), ('Settled', 'settled')], default=None, max_length=200)),
                ('Violation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VTraffic.officer_page')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reminders', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VTraffic.ticket')),
            ],
        ),
    ]
