# Generated by Django 3.1.6 on 2021-06-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VTraffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FineAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='communicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('EmailAddress', models.CharField(max_length=200)),
                ('GiveUsFeedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='violator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='First_Page',
            new_name='main',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Violation',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Ticket',
        ),
        migrations.RenameModel(
            old_name='Officer_Page',
            new_name='Officer',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.AddField(
            model_name='violator',
            name='Ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='VTraffic.officer'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='Violation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VTraffic.officer'),
        ),
    ]
